version: '3'
services:
  front:
    image: node:12.4.0-alpine
    container_name: vision-front
    build: ./vision-front
    ports:
      - 8080:8080
    volumes:
      - ./vision-front:/app
    stdin_open: true
    privileged: true
    tty: true
    command: npm run serve 
    environment:
      VUE_APP_API: http://localhost:8000


  vision-api:
    build: ./vision-api
    ports:
      - 8000:8000
    volumes:
      - ./vision-api:/myapp
    command: python ./vision_app/manage.py runserver 0.0.0.0:8000
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    container_name: vision-api
    tty: true
    stdin_open: true
    privileged: true

  #nginx:
  #  image: nginx:1.13
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - ./nginx/conf:/etc/nginx/conf.d
  #  depends_on:
  #    - vision-api


