version: '3'
services:
  front:
    image: node:12.4.0-alpine
    container_name: vision-front
    image: inatetsu/vision-front
    # build: ./vision-front
    ports:
      - 8080:8080
    volumes:
      - ./vision-front:/app
    stdin_open: true
    privileged: true
    tty: true
    # command: npm run serve 
    environment:
      VUE_APP_API: http://localhost:8000


  vision-api:
    # build: ./vision-api
    image: inatetsu/vision-api
    ports:
      - 8000:8000
    volumes:
      - ./vision-api:/myapp
    command: python ./vision_app/manage.py runserver 0.0.0.0:8000
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    container_name: vision-api
    tty: true
    stdin_open: true
    privileged: true
    depends_on:
      - news-db
    environment:
      - DB_news_NAME=news
      - DB_wiki_NAME=wiki
      - DB_USER=root
      - DB_PASS=password
      - DB_wiki_HOST=wiki-db
      - DB_news_HOST=news-db

  news-db:
    build: ./news_db
    volumes:
      - ./news_db/data:/var/lib/mysql
      - ./news_db/conf:/etc/mysql/conf.d
      - ./news_db/init:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306

  #nginx:
  #  image: nginx:1.13
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - ./nginx/conf:/etc/nginx/conf.d
  #  depends_on:
  #    - vision-api


